baseURL = 'https://woxihuanshuijiao.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "目录" # 网页上显示的按钮名字
    url = "/categories/" 
    weight = 10 
