baseURL = 'https://woxihuanshuijiao.github.io/'
languageCode = 'en-us'
title = '菡's Land'
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "目录" # 网页上显示的按钮名字
    url = "/categories/" 
    weight = 10 

[params.label]
  text = "Phantom Frontier - 幽灵地带"
  icon = "static/favicon.png"