baseURL = 'https://woxihuanshuijiao.github.io/'
languageCode = 'en-us'
title = "Phantom Frontier - 幽灵地带"
theme = "PaperMod"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "目录" # 网页上显示的按钮名字
    url = "/categories/" 
    weight = 10 

[params.label]
  text = "菡's Land"
  icon = "https://raw.githubusercontent.com/woxihuanshuijiao/woxihuanshuijiao.github.io/refs/heads/main/static/logo_final.png"

[params.assets]
  favicon = "https://raw.githubusercontent.com/woxihuanshuijiao/woxihuanshuijiao.github.io/refs/heads/main/static/favicon.png"